plugins { id 'com.android.library' }

android {
    namespace 'dev.bluehouse.enablevolte.xposed'
    compileSdk 36
    defaultConfig { minSdk 28 }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
dependencies { compileOnly 'de.robv.android.xposed:api:82' }
